import * as XLSX from "xlsx";
import { ReportData } from "@/actions/reports";
import { format, parseISO } from "date-fns";
import { enUS } from "date-fns/locale";

export function exportToExcel(data: ReportData) {
  const workbook = XLSX.utils.book_new();

  // Summary Sheet
  const summaryData = [
    ["Financial Report Summary"],
    ["Yacht", data.yacht.name],
    ["Report Date", format(parseISO(data.generatedAt), "dd MMMM yyyy, HH:mm", { locale: enUS })],
    ["Generated By", data.generatedBy.name || data.generatedBy.email],
    [],
    ["Total Income", data.summary.totalIncome],
    ["Total Expenses", data.summary.totalExpenses],
    ["Net Balance", data.summary.netBalance],
    ["Expense Count", data.summary.expenseCount],
    ["Transaction Count", data.summary.transactionCount],
  ];

  const summarySheet = XLSX.utils.aoa_to_sheet(summaryData);
  XLSX.utils.book_append_sheet(workbook, summarySheet, "Summary");

  // Expenses by Category Sheet
  const categoryData = [
    ["Category", "Amount", "Transaction Count"],
    ...data.expensesByCategory.map((item) => [
      item.categoryName,
      item.totalAmount,
      item.count,
    ]),
  ];
  const categorySheet = XLSX.utils.aoa_to_sheet(categoryData);
  XLSX.utils.book_append_sheet(workbook, categorySheet, "Category Distribution");

  // Expenses by Month Sheet
  const monthlyData = [
    ["Month", "Amount", "Transaction Count"],
    ...data.expensesByMonth.map((item) => [
      format(parseISO(`${item.month}-01`), "MMMM yyyy", { locale: enUS }),
      item.amount,
      item.count,
    ]),
  ];
  const monthlySheet = XLSX.utils.aoa_to_sheet(monthlyData);
  XLSX.utils.book_append_sheet(workbook, monthlySheet, "Monthly Trend");

  // Detailed Expenses Sheet
  const expensesData = [
    [
      "Date",
      "Description",
      "Category",
      "Vendor",
      "Invoice Number",
      "Payment Method",
      "Paid By",
      "Amount",
      "Currency",
    ],
    ...data.expenses.map((exp) => [
      format(parseISO(exp.date), "dd/MM/yyyy"),
      exp.description,
      exp.categoryName,
      exp.vendorName || "",
      exp.invoiceNumber || "",
      exp.paymentMethod.replace("_", " "),
      exp.paidBy.replace("_", " "),
      exp.amount,
      exp.currency,
    ]),
  ];
  const expensesSheet = XLSX.utils.aoa_to_sheet(expensesData);
  XLSX.utils.book_append_sheet(workbook, expensesSheet, "Detailed Expenses");

  // Cash Transactions Sheet
  if (data.cashTransactions.length > 0) {
    const cashData = [
      ["Date", "Type", "Amount", "Currency", "Description"],
      ...data.cashTransactions.map((t) => [
        format(parseISO(t.date), "dd/MM/yyyy"),
        t.type,
        t.amount,
        t.currency,
        t.description || "",
      ]),
    ];
    const cashSheet = XLSX.utils.aoa_to_sheet(cashData);
    XLSX.utils.book_append_sheet(workbook, cashSheet, "Cash Transactions");
  }

  // Generate filename
  const filename = `${data.yacht.name}_Report_${format(parseISO(data.generatedAt), "yyyy-MM-dd")}.xlsx`;

  // Save file
  XLSX.writeFile(workbook, filename);
}

